Md = input('What\'s your name?')
dsc = input('Describe yourself')
F = open('wb.html','w') 
F.write('<html>')
F.write('<body>')
F.write("<h1>")
F.write(Md)
F.write('</h1>')
F.write('<hr />')
F.write(dsc)
F.write('<hr />')
F.write('</body>')
F.write('</html>')
F.close()