M = input("What is your name?")
E= input("What do you do?")
FF = open("M.html","w")
FF.write("<html>")
FF.write("<h1>")
FF.write(M)
FF.write("</h1>")
FF.write("<h2>")
FF.write("</h2>")
FF.write("<body>")
FF.write(E)
FF.write("</body>")
FF.write("</html>")

